src/Web/Sfa.Das.Sas.Web/Views/Provider/Detail.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Provider/Detail.generated.cs, src/Web/Sfa.Das.Sas.Web/Views/Provider/_FrameworkSearchResultMessage.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Provider/_FrameworkSearchResultMessage.generated.cs, src/Web/Sfa.Das.Sas.Web/Views/Provider/_StandardSearchResultMessage.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Provider/_StandardSearchResultMessage.generated.cs, src/Web/Sfa.Das.Sas.Web/Views/Start/Start.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Start/Start.generated.cs
Additional Notes:
* ProviderFrameworkSearchResultViewModel and ProviderStandardSearchResultViewModel have a ShowAll property which may be redundant on the ViewModel.
=> FAT-160 - Copy changes for search pages on Find Apprentice Training site

src/Web/Sfa.Das.Sas.ApplicationServices/Models/FrameworkProviderSearchResultsItem.cs, src/Web/Sfa.Das.Sas.ApplicationServices/Models/IApprenticeshipProviderSearchResultsItem.cs, src/Web/Sfa.Das.Sas.ApplicationServices/Models/StandardProviderSearchResultsItem.cs, src/Web/Sfa.Das.Sas.Core/Domain/Model/Provider.cs, src/Web/Sfa.Das.Sas.Infrastructure/Mapping/ProviderMapping.cs, src/Web/Sfa.Das.Sas.Resources/EquivalenceLevelService.cs, src/Web/Sfa.Das.Sas.Resources/Sfa.Das.Sas.Resources.csproj, src/Web/Sfa.Das.Sas.Web.UnitTests/Infrastructure/Resources/EquivalenceLevelTest.cs, src/Web/Sfa.Das.Sas.Web.UnitTests/Infrastructure/Web/Views/Provider/ProviderDetailsPage.cs, src/Web/Sfa.Das.Sas.Web.UnitTests/Sfa.Das.Sas.Web.UnitTests.csproj, src/Web/Sfa.Das.Sas.Web/Services/MappingService.cs, src/Web/Sfa.Das.Sas.Web/ViewModels/ApprenticeshipDetailsViewModel.cs, src/Web/Sfa.Das.Sas.Web/Views/Apprenticeship/Framework.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Apprenticeship/Framework.generated.cs, src/Web/Sfa.Das.Sas.Web/Views/Apprenticeship/Standard.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Apprenticeship/Standard.generated.cs, src/Web/Sfa.Das.Sas.Web/Views/Provider/Detail.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Provider/Detail.generated.cs
Additional Notes:
- Relies on https://github.com/SkillsFundingAgency/das-apprenticeship-programs-api/pull/16
=> CI-145 - Adding Legal Trading Name To Provider Details Page

src/Web/Sfa.Das.Sas.Web.CloudService/ServiceConfiguration.Cloud.cscfg, src/Web/Sfa.Das.Sas.Web.CloudService/ServiceConfiguration.Local.cscfg
=> CI-357 Updating QAR source link

src/Web/Sfa.Das.Sas.Web/Global.asax.cs
Currently only logging HttpException but missing other (like HttpRequestException)
* Please have I think of the implications
* Will this increase the amount of error log we get?
* Any other way we can make sure we logging all the errors?
=> Logging all errors

src/Web/Sfa.Das.Sas.Web/NLog.config
* To be able to find local log files easier.
* can save log files for all application in the same folder so that its easier to move between different applications logs.
* New folder every day.
=> Local logs to temp folder, logging properties in local file

src/Web/Sfa.Das.Sas.Web/Views/Provider/_FrameworkProviderInformation.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Provider/_FrameworkProviderInformation.generated.cs
=> CI-410 fix now in place

src/Web/Sfa.Das.Sas.Web.UnitTests/Infrastructure/Web/Services/Mapping/ForApprenticeshipMappingHelper.cs, src/Web/Sfa.Das.Sas.Web/Services/MappingActions/Helpers/ApprenticeshipMappingHelper.cs, src/Web/Sfa.Das.Sas.Web/Views/Provider/ProviderDetail.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Provider/ProviderDetail.generated.cs
Chaps, I did the provider name work on this story by mistake, so don't be surprised when you see that code in here 🍺
=> Ci 519 mapping issue in searchforframeworkproviders

src/Web/Sfa.Das.Sas.Web/Views/Apprenticeship/Standard.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Apprenticeship/Standard.generated.cs
Hi Mark,
I've re-ordered those sections by putting everything inside the description list tags (`<dl><dt>`).
Let me know if that all works okay at your end?
Cheers and have a good Easter 🐣,
Greg
=> Move 'get more information' above 'end point assessment'

src/Web/Sfa.Das.Sas.Web.UnitTests/Infrastructure/Web/Controllers/ApprenticeshipControllerTests.cs, src/Web/Sfa.Das.Sas.Web.UnitTests/Infrastructure/Web/Services/ButtonTextServiceTests.cs, src/Web/Sfa.Das.Sas.Web.UnitTests/Sfa.Das.Sas.Web.UnitTests.csproj, src/Web/Sfa.Das.Sas.Web/Controllers/ApprenticeshipController.cs, src/Web/Sfa.Das.Sas.Web/Services/ButtonTextService.cs, src/Web/Sfa.Das.Sas.Web/Services/IButtonTextService.cs, src/Web/Sfa.Das.Sas.Web/Sfa.Das.Sas.Web.csproj, src/Web/Sfa.Das.Sas.Web/ViewModels/FrameworkViewModel.cs, src/Web/Sfa.Das.Sas.Web/ViewModels/StandardViewModel.cs, src/Web/Sfa.Das.Sas.Web/Views/Apprenticeship/Framework.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Apprenticeship/Framework.generated.cs, src/Web/Sfa.Das.Sas.Web/Views/Apprenticeship/Standard.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Apprenticeship/Standard.generated.cs
So this is a comparison of CI-745 and CI-790, as CI-745 needs to go into it.
=> Ci 745 make find training providers button journey dependant

src/Web/Sfa.Das.Sas.Web/Views/Provider/ProviderDetail.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Provider/ProviderDetail.generated.cs
Removed a duplicate navigation section introduced by mistake when updating master_es2 from the es5 branch
=> CI-815 removed duplicate nav html

src/Web/Sfa.Das.Sas.Web/Services/MappingActions/ProviderSearchMappingHelper.cs
Paired with Dan A, pushing through minor change
=> Fix for pagination issue added

src/Web/Sfa.Das.Sas.Web.CloudService/Configuration/ServiceDefinition.Cloud.csdef, src/Web/Sfa.Das.Sas.Web.CloudService/Configuration/ServiceDefinition.Release.csdef, src/Web/Sfa.Das.Sas.Web.CloudService/ServiceConfiguration.Cloud.cscfg, src/Web/Sfa.Das.Sas.Web.CloudService/ServiceConfiguration.Local.cscfg, src/Web/Sfa.Das.Sas.Web.CloudService/ServiceConfiguration.PreProd.cscfg, src/Web/Sfa.Das.Sas.Web.CloudService/ServiceConfiguration.Prod.cscfg, src/Web/Sfa.Das.Sas.Web.CloudService/ServiceConfiguration.Release.cscfg, src/Web/Sfa.Das.Sas.Web.CloudService/ServiceDefinition.csdef, src/Web/Sfa.Das.Sas.Web/Global.asax.cs
Changed application insights key to be read from the CloudConfiguration settings instead of web config
=> CI 872 application insights

src/Web/Sfa.Das.Sas.Web/Global.asax.cs
=> CI-825 changed logging of these issues from warning to info

src/Web/Sfa.Das.Sas.ApplicationServices/Models/StandardSearchResultsItem.cs, src/Web/Sfa.Das.Sas.Core/Domain/Model/Standard.cs, src/Web/Sfa.Das.Sas.Infrastructure/Mapping/StandardMapping.cs, src/Web/Sfa.Das.Sas.Web.CloudService/ServiceConfiguration.Local.cscfg, src/Web/Sfa.Das.Sas.Web/Global.asax.cs, src/Web/Sfa.Das.Sas.Web/Services/MappingService.cs, src/Web/Sfa.Das.Sas.Web/ViewModels/StandardViewModel.cs, src/Web/Sfa.Das.Sas.Web/Views/Apprenticeship/Standard.cshtml, src/Web/Sfa.Das.Sas.Web/Views/Apprenticeship/Standard.generated.cs
this story also has a pull request in the indexer
=> Ci 836 remove old govuk publication links

src/Web/Sfa.Das.Sas.Web.CloudService/ServiceConfiguration.Cloud.cscfg
Update ServiceConfiguration.Cloud.cscfg WebSsl thumbprint
=> DEV: Domain migration

src/Web/Sfa.Das.Sas.Infrastructure/ElasticSearch/ElasticsearchApprenticeshipSearchProvider.cs, src/Web/Sfa.Das.Sas.Infrastructure/ElasticSearch/ProviderNameSearchProvider.cs, src/Web/Sfa.Das.Sas.Infrastructure/Helpers/QueryHelper.cs, src/Web/Sfa.Das.Sas.Infrastructure/Providers/ApprenticeshipsSearchApiProvider.cs, src/Web/Sfa.Das.Sas.Infrastructure/Sfa.Das.Sas.Infrastructure.csproj, src/Web/Sfa.Das.Sas.Shared.Components/Sfa.Das.Sas.Shared.Components.nuspec, src/Web/Sfa.Das.Sas.Shared.Components/ViewComponents/Fat/SearchResults/FatSearchResultsViewModel.cs, src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/Components/FatSearchResults/Default.cshtml, src/Web/Sfa.Das.Sas.Web.UnitTests/Infrastructure/Providers/Api/ApiApprenticeshipSearchProviderTests.cs
Applied same behaviour as FAT Website i.e. return all results
=> FC-614 blank search

src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/Components/FatSearchResults/Default.cshtml
I think this is a duplicate searchbox. @jamesmking can you confirm?
=> Bug - duplicate searchbox

src/Web/Sfa.Das.Sas.Shared.Components/Sfa.Das.Sas.Shared.Components.nuspec
This fixes an dependency version issue in the Campaign Tidy up branch
=> Update dependant package version

src/Web/Sfa.Das.Sas.ApplicationServices/Handlers/AddFavouriteToBasketCommandHandler.cs, src/Web/Sfa.Das.Sas.ApplicationServices/Handlers/GetBasketHandler.cs, src/Web/Sfa.Das.Sas.ApplicationServices/Queries/GetBasketQuery.cs, src/Web/Sfa.Das.Sas.ApplicationServices/Sfa.Das.Sas.ApplicationServices.csproj, src/Web/Sfa.Das.Sas.Infrastructure/Sfa.Das.Sas.Infrastructure.csproj, src/Web/Sfa.Das.Sas.Shared.Basket/ApprenticehipFavouritesBasketStoreConfig.cs, src/Web/Sfa.Das.Sas.Shared.Basket/ApprenticeshipFavourite.cs, src/Web/Sfa.Das.Sas.Shared.Basket/ApprenticeshipFavouritesBasket.cs, src/Web/Sfa.Das.Sas.Shared.Basket/ApprenticeshipFavouritesBasketStore.cs, src/Web/Sfa.Das.Sas.Shared.Basket/IApprenticeshipFavouritesBasketStore.cs, src/Web/Sfa.Das.Sas.Shared.Basket/ServiceCollectionExtensions.cs, src/Web/Sfa.Das.Sas.Shared.Basket/Sfa.Das.Sas.Shared.Basket.csproj, src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/ViewComponents/AddToBasket/AddToBasketViewComponentTests.cs, src/Web/Sfa.Das.Sas.Shared.Components/DependencyResolution/SharedComponentsRegistry.cs, src/Web/Sfa.Das.Sas.Shared.Components/Sfa.Das.Sas.Shared.Components.csproj, src/Web/Sfa.Das.Sas.Shared.Components/Sfa.Das.Sas.Shared.Components.nuspec, src/Web/Sfa.Das.Sas.Web.UnitTests/Application/Handlers/AddFavouriteToBasketHandlerTests.cs, src/Web/Sfa.Das.Sas.Web.UnitTests/Application/Handlers/GetBasketHandlerTests.cs, src/Web/Sfa.Das.Sas.Web.UnitTests/Sfa.Das.Sas.Web.UnitTests.csproj, src/Web/Sfa.Das.Sas.Web.sln
Moved code to retrieve/save basket contents into own library so can be packaged and re-used in das-employer-favourites
=> FC-434 Basket Access Package

src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/ViewComponents/AddToBasket/AddToBasketViewComponentTests.cs, src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/ViewComponents/SaveBasket/SaveBasketViewComponentTests.cs, src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/ViewComponents/ViewComponentTestsBase.cs, src/Web/Sfa.Das.Sas.Shared.Components/Sfa.Das.Sas.Shared.Components.nuspec, src/Web/Sfa.Das.Sas.Shared.Components/ViewComponents/Basket/SaveBasketViewComponent.cs, src/Web/Sfa.Das.Sas.Shared.Components/ViewComponents/Basket/SaveBasketViewModel.cs, src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/Components/SaveBasket/Default.cshtml
- New 'Save Basket' View component
=> FC-434 Save Basket

src/Web/Sfa.Das.Sas.ApplicationServices/Handlers/AddorRemoveFavouriteInBasketCommandHandler.cs, src/Web/Sfa.Das.Sas.ApplicationServices/Responses/GetClosestLocationsResponse.cs, src/Web/Sfa.Das.Sas.Shared.Basket/ApprenticeshipFavouritesBasket.cs, src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/Controller/BasketControllerTests.cs, src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/Mapping/TrainingProvider/GivenClosestLocationResponseMappedToViewModel.cs, src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/Orchestrator/TrainingProviderOrchestratorTests.cs, src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/ViewComponents/TrainingProvider/ClosestLocationsComponentTests.cs, src/Web/Sfa.Das.Sas.Shared.Components/Controllers/BasketController.cs, src/Web/Sfa.Das.Sas.Shared.Components/Mapping/Interfaces/ITrainingProviderClosestLocationsViewModelMapper.cs, src/Web/Sfa.Das.Sas.Shared.Components/Mapping/TrainingProviderClosestLocationsViewModelMapper.cs, src/Web/Sfa.Das.Sas.Shared.Components/Orchestrators/ITrainingProviderOrchestrator.cs, src/Web/Sfa.Das.Sas.Shared.Components/Orchestrators/TrainingProviderOrchestrator.cs, src/Web/Sfa.Das.Sas.Shared.Components/Sfa.Das.Sas.Shared.Components.nuspec, src/Web/Sfa.Das.Sas.Shared.Components/ViewComponents/TrainingProvider/ClosestLocations/CloseLocationViewModel.cs, src/Web/Sfa.Das.Sas.Shared.Components/ViewComponents/TrainingProvider/ClosestLocations/ClosestLocationsViewComponent.cs, src/Web/Sfa.Das.Sas.Shared.Components/ViewComponents/TrainingProvider/ClosestLocations/ClosestLocationsViewModel.cs, src/Web/Sfa.Das.Sas.Shared.Components/ViewModels/Basket/SaveBasketFromProviderDetailsViewModel.cs, src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/Components/TrainingProvider/ClosestLocations/Default.cshtml, src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/Components/TrainingProvider/SearchResults/_searchResultsItem.cshtml, src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/TrainingProvider/Details.cshtml, src/Web/Sfa.Das.Sas.Web.UnitTests/Application/Handlers/AddOrRemoveFavouriteInBasketHandlerTests.cs
Fix issue with add to favourites in the nearest locations list.
Tidy up unit test assertion errors.
=> FC-817 Fix issues and tidy up

src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/Components/Basket/BasketIcon/Default.cshtml
=> FC-915 Update to markup of the favourites icon

src/Web/Sfa.Das.Sas.Shared.Components/Sfa.Das.Sas.Shared.Components.nuspec, src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/Components/TrainingProvider/Details/Default.cshtml, src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/Components/TrainingProvider/Details/Summary.cshtml, src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/TrainingProvider/Details.cshtml
adds message box to show that the provider is not accepting new starters and rearranges the title
=> Fc 722 provider search not showing not accepting new starters alert

src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/Orchestrator/TrainingProviderOrchestratorTests.cs, src/Web/Sfa.Das.Sas.Shared.Components/Orchestrators/TrainingProviderOrchestrator.cs, src/Web/Sfa.Das.Sas.Shared.Components/Sfa.Das.Sas.Shared.Components.nuspec
This adds the IsLevyPayingEmployer parameter into the search query model.
=> Fc 1127 training provider not showing up in fiu fat search

src/Web/Sfa.Das.Sas.Shared.Components.Web/Views/Shared/TrainingProvider/Details.cshtml
adds hidden input for postcode
=> FC-1198_Locations_disappearing_on_add_to_favourites

src/Web/Sfa.Das.Sas.ApplicationServices/Commands/AddOrRemoveFavouriteInBasketCommand.cs, src/Web/Sfa.Das.Sas.ApplicationServices/Handlers/AddorRemoveFavouriteInBasketCommandHandler.cs, src/Web/Sfa.Das.Sas.Shared.Basket/Sfa.Das.Sas.Shared.Basket.csproj, src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/Controller/BasketControllerTests.cs, src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/Orchestrator/ApprenticeshipOrchestratorTests.cs, src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/Orchestrator/BasketOrchestratorTests.cs, src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/Orchestrator/TrainingProviderOrchestratorTests.cs, src/Web/Sfa.Das.Sas.Shared.Components.Web/Views/Shared/Fat/ApprenticeshipDetails.cshtml, src/Web/Sfa.Das.Sas.Shared.Components.Web/Views/Shared/Fat/SearchResults.cshtml, src/Web/Sfa.Das.Sas.Shared.Components/Controllers/BasketController.cs, src/Web/Sfa.Das.Sas.Shared.Components/Controllers/FatController.cs, src/Web/Sfa.Das.Sas.Shared.Components/Orchestrators/BasketOrchestrator.cs, src/Web/Sfa.Das.Sas.Shared.Components/Orchestrators/FatOrchestrator.cs, src/Web/Sfa.Das.Sas.Shared.Components/Orchestrators/IBasketOrchestrator.cs, src/Web/Sfa.Das.Sas.Shared.Components/Sfa.Das.Sas.Shared.Components.nuspec, src/Web/Sfa.Das.Sas.Shared.Components/ViewComponents/Fat/Search/FatSearchViewModel.cs, src/Web/Sfa.Das.Sas.Shared.Components/ViewModels/ApprenticeshipDetailQueryViewModel.cs, src/Web/Sfa.Das.Sas.Shared.Components/ViewModels/SearchQueryViewModel.cs, src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/Components/FatSearchResults/Default.cshtml, src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/Fat/ApprenticeshipDetails.cshtml, src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/Fat/SearchResults.cshtml, src/Web/Sfa.Das.Sas.Web.UnitTests/Application/Handlers/AddOrRemoveFavouriteInBasketHandlerTests.cs, src/Web/Sfa.Das.Sas.Web/Web.config
=> FC-1331 Change to add / remove from basket to show notification

src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/Orchestrator/ApprenticeshipOrchestratorTests.cs, src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/Orchestrator/BasketOrchestratorTests.cs, src/Web/Sfa.Das.Sas.Shared.Components.UnitTests/Orchestrator/TrainingProviderOrchestratorTests.cs, src/Web/Sfa.Das.Sas.Shared.Components/Mapping/ApprenticeshipBasketItemViewModelMapper.cs, src/Web/Sfa.Das.Sas.Shared.Components/Mapping/Interfaces/ITrainingProviderDetailsViewModelMapper.cs, src/Web/Sfa.Das.Sas.Shared.Components/Mapping/TrainingProviderDetailsViewModelMapper.cs, src/Web/Sfa.Das.Sas.Shared.Components/Orchestrators/TrainingProviderOrchestrator.cs, src/Web/Sfa.Das.Sas.Shared.Components/Sfa.Das.Sas.Shared.Components.nuspec, src/Web/Sfa.Das.Sas.Shared.Components/ViewComponents/TrainingProvider/Details/TrainingProviderDetailsViewModel.cs, src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/Components/Basket/Details/_apprenticeshipItem.cshtml, src/Web/Sfa.Das.Sas.Shared.Components/Views/Shared/Components/TrainingProvider/Details/Default.cshtml
adds link back to provider details
=> FC-896 adds link back to provider details
